#ifndef EXPLAIN_AST_DECLS_INC
#define EXPLAIN_AST_DECLS_INC

namespace explain {

namespace AST {

class Node;
class Root;
class BlockStmt;
class FuncDeclArgs;
class FuncCallArgs;
class Entry;
class Stmt;
class FuncDecl;
class AssignmentStmt;
class IfStmt;
class WhileStmt;
class ReturnStmt;
class IOStmt;
class Expr;
class ExprBinOp;
class ExprIdent;
class ExprNumber;
class ExprFuncCall;
class Cond;
class CondUnOp;
class CondBinOp;
class CondCompOp;

} // end namespace AST

} // end namespace explain

#endif //EXPLAIN_AST_DECLS_INC
